config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  get "about", to: "home#about"
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :is_friend_of_the_current_user, only: %i[ edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = current_user.nil? ? Friend.all : current_user.friends
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy!

    respond_to do |format|
      format.html { redirect_to friends_path, status: :see_other, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_friend
    @friend = Friend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def friend_params
    params.require(:friend).permit(:first_name, :last_name, :phone, :twitter, :user_id)
  end

  def is_friend_of_the_current_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "You can not modify this friend!" if @friend.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :last_name, class: "form-label" %>
    <%= form.text_field :last_name, class: "form-control" %>
  </div>

  <div>
    <%= form.label :phone, class: "form-label" %>
    <%= form.text_field :phone, class: "form-control" %>
  </div>

  <div>
    <%= form.label :twitter, class: "form-label" %>
    <%= form.text_field :twitter, class: "form-control" %>
  </div>

  <div>
    <%= form.text_field :user_id, class: "form-control", value: current_user.id, type: "hidden" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary mt-3" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>" class="p-5 mb-4 bg-light rounded-3">
  <h1 class="display-5 fw-bold">
    <%= friend.first_name %>
    <%= friend.last_name %>
  </h1>

  <p class="fs-4">
    <%= friend.phone %> | <%= friend.twitter %>
  </p>
</div>

app/views/friends/edit.html.erb
<% content_for :title, "Editing friend" %>

<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-secondary" %>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/index.html.erb
<% content_for :title, "Friends" %>

<h1>Friends</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Friend of</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
    <tr>
      <td><%= friend.first_name %></td>
      <td><%= friend.last_name %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td><%= friend.user_id %></td>
      <td>
        <div class="d-flex gap-2">
          <%= link_to "Details", friend, class: "btn btn-primary" %>
          <%= button_to "Delete", friend, method: :delete, class: "btn btn-danger" %>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New friend", new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<% content_for :title, "New friend" %>

<h1>Add new friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

<div>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-primary" %>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>

  <%= button_to "Destroy this friend", @friend, method: :delete, class: "btn btn-danger mt-2" %>
</div>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>New index page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <title><%= content_for(:title) || "friends_app" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= yield :head %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'partials/header' %>
    <div class="container mt-2">
      <% if notice %>
        <%= render "partials/notice" %>
      <% end %>
      <% if alert %>
        <%= render "partials/alert" %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_alert.html.erb
<div class="alert alert-warning" role="alert">
    <%= alert %>
</div>

app/views/partials/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <%= link_to 'Friends', root_path, class: "navbar-brand" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item mx-2">
              <%= link_to 'About', about_path, class: "navbar-link navbar-link btn btn-link p-0" %>
            </li>
            <li class="nav-item mx-2">
              <%= link_to 'Friends', friends_path, class: "navbar-link navbar-link btn btn-link p-0" %>
            </li>
            <% if user_signed_in? %>
              <li class="nav-item mx-2">
                <%= link_to 'Add Friends', new_friend_path, class: "navbar-link navbar-link btn btn-link p-0" %>
              </li>
              <li class="nav-item mx-2">
                <%= link_to 'Edit Profile', edit_user_registration_path, class: "navbar-link navbar-link btn btn-link p-0" %>
              </li>
              <li class="nav-item mx-2">
                <%= button_to "Sign out", destroy_user_session_path, :method => "delete", class: "navbar-link btn btn-link p-0"  %>
              </li>
            <% else %>
            <li class="nav-item mx-2">
              <%= link_to 'Sign In', new_user_session_path, class: "navbar-link navbar-link btn btn-link p-0" %>
            </li>
            <li class="nav-item mx-2">
              <%= link_to 'Sign Up', new_user_registration_path, class: "navbar-link navbar-link btn btn-link p-0" %>
            </li>
            <% end %>
          </ul>   
        </div>
      </div>
    </nav>
</header>

app/views/partials/_notice.html.erb
<div class="alert alert-success" role="alert">
    <%= notice %>
</div>